name: Extract and Replace M3U
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "Logo/*.*"
      - "M3U/ipv6.m3u"
      - "README.md"

jobs:
  extract_and_replace:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create tmp directory if not exists
      run: mkdir -p ./tmp

    - name: Extract and process M3U
      run: |
        curl -s https://raw.githubusercontent.com/YueChan/Live/main/IPTV.m3u | grep -E 'group-title="(央视|国际|卫视|地方|数字)".*http://' > ./tmp/tmp.txt
        mv ./tmp/tmp.txt ./tmp/$(date +"%Y%m%d%H%M%S").txt

    - name: Replace M3U file
      run: |
        sed -i 's@./M3U/YueChan_ipv6.m3u@./tmp/$(ls -t ./tmp | head -n1)@' ./M3U/YueChan_ipv6.m3u
