name: Extract and Replace M3U
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "Logo/*.*"
      - "M3U/ipv6.m3u"
      - "README.md"

jobs:
  extract_and_replace:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests
      shell: bash

    - name: Extract and Replace M3U
      run: |
        # Create tmp directory if it doesn't exist
        mkdir -p tmp

        # Download the IPTV.m3u file
        wget https://raw.githubusercontent.com/YueChan/Live/main/IPTV.m3u -O tmp/IPTV.m3u

        # Extract lines with group-title containing '央视', '国际', '卫视', '地方', and containing 'http://' or 'm3u8?' into separate files
        grep -E 'group-title: (央视|国际|卫视|地方|数字).*http://|m3u8\?' tmp/IPTV.m3u | awk -F ',' '{print > "./tmp/" $6}'

        # Replace the content of YueChan_ipv6.m3u with the content of tmp directory
        cat tmp/* > M3U/YueChan_ipv6.m3u

        # Clean up tmp directory
        rm -rf tmp
      shell: bash
        sed -i 's@./M3U/YueChan_ipv6.m3u@./tmp/$(ls -t ./tmp | head -n1)@' ./M3U/YueChan_ipv6.m3u
