name: Extract and Replace M3U
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "Logo/*.*"
      - "M3U/ipv6.m3u"
      - "README.md"

jobs:
  extract_and_replace:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Create tmp directory
      run: mkdir -p ./tmp
    
    - name: Install dependencies
      run: pip install requests
    
    - name: Extract and Replace
      run: |
        python extract_replace.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Delete tmp directory
      run: rm -rf ./tmp
